# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hicData <- function(fileName, chr1, chr2, unit, resolution) {
    .Call(`_FreeHiCLite_hicData`, fileName, chr1, chr2, unit, resolution)
}

hicDataHttp <- function(fileName, chr1, chr2, unit, resolution) {
    .Call(`_FreeHiCLite_hicDataHttp`, fileName, chr1, chr2, unit, resolution)
}

hicDataExtra <- function(fileName, isHttp, pair, unit, resolution) {
    .Call(`_FreeHiCLite_hicDataExtra`, fileName, isHttp, pair, unit, resolution)
}

hicDataFragSites <- function(fileName, isHttp, chromosomes) {
    .Call(`_FreeHiCLite_hicDataFragSites`, fileName, isHttp, chromosomes)
}

hicDataInformation <- function(fileName, isHttp) {
    .Call(`_FreeHiCLite_hicDataInformation`, fileName, isHttp)
}

hicDataSimuFromFile <- function(fileName, isHttp, pair, unit, resolution, sequenceDepth, countScale, noiseRate, neighborZeroRate) {
    .Call(`_FreeHiCLite_hicDataSimuFromFile`, fileName, isHttp, pair, unit, resolution, sequenceDepth, countScale, noiseRate, neighborZeroRate)
}

hicDataSimuList <- function(contactRecords, names, resolution, sequenceDepth, countScale, noiseRate, neighborZeroRate) {
    .Call(`_FreeHiCLite_hicDataSimuList`, contactRecords, names, resolution, sequenceDepth, countScale, noiseRate, neighborZeroRate)
}

hicDataSimuMatrix <- function(contactRecords, resolution, sequenceDepth, countScale, noiseRate, neighborZeroRate) {
    .Call(`_FreeHiCLite_hicDataSimuMatrix`, contactRecords, resolution, sequenceDepth, countScale, noiseRate, neighborZeroRate)
}

spikein <- function(background, SpikeInSignal, bandwith, smooth) {
    .Call(`_FreeHiCLite_spikein`, background, SpikeInSignal, bandwith, smooth)
}

